[opener]
imv_image = [
  { run = 'imv "$0"', desc = "imv Image Viewer", block = false, for = "unix" },
]

mpv_video = [
  { run = 'mpv "$0"', desc = "mpv Video Player", block = false, for = "unix" },
]

zathura_pdf = [
  { run = 'zathura "$0"', desc = "Zathura PDF Reader", block = false, for = "unix" },
]

micro = [
  { run = 'micro "$0"', desc = "Micro editor", block = true, for = "unix" },
]

edit = [ { run = 'micro "$@"', block = true, desc = "Micro" } ]

[open]
prepend_rules = [
  # Images → imv
  { mime = "image/*", use = "imv_image" },

  # Videos → mpv
  { mime = "video/*", use = "mpv_video" },

  # PDFs → zathura
  { mime = "application/pdf", use = "zathura_pdf" },

  # Code files → micro
  { mime = "text/*", use = "micro" },
]

[mgr]
show_hidden = false
linemode = "size_and_mtime"

[theme]
use = "catppuccin-mocha"

[icons]
use = "catppuccin"

